version: '2'

services:

### Applications Code Container #############################

    aplicaciones:
        image: tianon/true
        volumes:
            - ./web:/var/www
#            - ../landing-viewer/:/var/www/landing-viewer
#            - ../demo-ci/:/var/www/demo-ci
#            - ../demo-ci-dev/:/var/www/demo-ci-dev
#            - ../demo-ci-pre/:/var/www/demo-ci-pre


    servidor:
        build:
            context: ./server
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_NODE=true
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
                - TZ=UTC
#                - API_TOKEN_COMPOSER=
        volumes_from:
            - aplicaciones
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            # OBTENER CON: docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
            - "dockerhost:172.19.0.2"
        ports:
           - "2224:22"
        tty: true


    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=demo
                - MYSQL_USER=dev
                - MYSQL_PASSWORD=123456
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.19.0.3"

    php:
        build:
            context: ./php
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_SOAP=true
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_BCMATH=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=true
                - INSTALL_AEROSPIKE_EXTENSION=false
            dockerfile: Dockerfile
        volumes_from:
            - aplicaciones
        expose:
            - "9000"
        links:
            - servidor
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.19.0.4"
        ports:
          - "80:80"
          - "443:443"
        links:
          - mysql


volumes:
    mysql:
        driver: "local"